Pin Poetry version
There seems to be an issue either in Poetry or `packaging` (which is a transitive dependency, which causes the following error in the GHA workflow:

```
No module named 'packaging.licenses'
Error: The process '/opt/pipx_bin/poetry' failed with exit code 1
```

I’m pinning Poetry to the previous version as a temporary workaround.